name: "CI - Continuous Integration"
on:
  push:
    branches: [main, develop]
  pull_request:
    types: [opened, synchronize, ready_for_review, reopened]

env:
  GO_VERSION: 1.23.x

jobs:
  tests:
    name: Running Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Golang
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          only-new-issues: true
